#!/bin/bash
set -e
tag_name=$1
echo $tag_name > ~/.boj/tag_name
cd ~/
if [ ! -d $tag_name ]; then
  git clone https://github.com/biran0079/boj.git --depth 1 -b $tag_name $tag_name
fi
cd $tag_name
./package
./stop
./start &

ln -sf $(pwd)/deploy ~/.boj/deploy
